spring.application.name=statistics-service
server.port=8085
spring.config.import=optional:configserver:http://localhost:8888

resilience4j.ratelimiter.instances.calculateTotalDonations.limitForPeriod=10
resilience4j.ratelimiter.instances.calculateTotalDonations.limitRefreshPeriod=5s

resilience4j.ratelimiter.instances.volunteersByCities.limitForPeriod=10
resilience4j.ratelimiter.instances.volunteersByCities.limitRefreshPeriod=5s

resilience4j.ratelimiter.instances.volunteersOnEvent.limitForPeriod=20
resilience4j.ratelimiter.instances.volunteersOnEvent.limitRefreshPeriod=5s

resilience4j.ratelimiter.instances.presentVolunteers.limitForPeriod=3
resilience4j.ratelimiter.instances.presentVolunteers.limitRefreshPeriod=5s

resilience4j.ratelimiter.instances.startedEvents.limitForPeriod=3
resilience4j.ratelimiter.instances.startedEvents.limitRefreshPeriod=5s